BEGIN TRANSACTION;
CREATE TABLE PESADAS (
        vin             CHAR(17) Not Null,
        modelo          VARCHAR(20) Not Null,
        fechahora       CHAR(20) PRIMARY KEY,
        vasos	        CHAR(1) Not Null,
        repeticiones    CHAR(1) Not Null,
        horainicio      VARCHAR(20) null,
        horafin	        VARCHAR(20) null,
        usuario	        VARCHAR(20) Not Null,
        F1Pi	        VARCHAR(8) default "",
        tF1Pi	        VARCHAR(4) default "",
        dpF1Pi	        VARCHAR(5) default "",
        F1Pf	        VARCHAR(8) default "",
        tF1Pf	        VARCHAR(4) default "",
        dpF1Pf	        VARCHAR(5) default "",
        F1Si	        VARCHAR(8) default "",
        tF1Si	        VARCHAR(4) default "",
        dpF1Si	        VARCHAR(5) default "",
        F1Sf	        VARCHAR(8) default "",
        tF1Sf	        VARCHAR(4) default "",
        dpF1Sf		    VARCHAR(5) default "",
        F2Pi	        VARCHAR(8) default "",
        tF2Pi	        VARCHAR(4) default "",
        dpF2Pi	        VARCHAR(5) default "",
        F2Pf	        VARCHAR(8) default "",
        tF2Pf	        VARCHAR(4) default "",
        dpF2Pf	        VARCHAR(5) default "",
        F2Si	        VARCHAR(8) default "",
        tF2Si	        VARCHAR(4) default "",
        dpF2Si	        VARCHAR(5) default "",
        F2Sf	        VARCHAR(8) default "",
        tF2Sf	        VARCHAR(4) default "",
        dpF2Sf	        VARCHAR(5) default "",
        R1i	            VARCHAR(8) default "",
        tR1i	        VARCHAR(4) default "",
        dpR1i	        VARCHAR(5) default "",
        R1f	            VARCHAR(8) default "",
        tR1f	        VARCHAR(4) default "",
        dpR1f	        VARCHAR(5) default "",
        R2i	            VARCHAR(8) default "",
        tR2i	        VARCHAR(4) default "",
        dpR2i	        VARCHAR(5) default "",
        R2f	            VARCHAR(8) default "",
        tR2f	        VARCHAR(4) default "",
        dpR2f           VARCHAR(5) default "",
        terminado       CHAR(1) null
        );
COMMIT;
