#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Jun  1 10:47:25 2010

import wx
import wx.grid as Grid
import time
try:
    import cPickle as pickle
except:
    import pickle
import gestionbbdd as gesbbdd

archivo = file("config.txt", 'r')        #archivo donde se encuentran las
datos = pickle.load(archivo)            #configuraciones iniciales.
BASEDEDATOS = datos['BASEDATOS']        #Nombre de la base de datos
VASOS = datos['IDVASOS']        # Items de vasos disponibles  
dic = datos['dic']              # estructura de diccionario para la base
llaves = datos['llaves']        # columnas de la base de datos (ordenadas).
archivo.close()
# begin wxGlade: extracode
# end wxGlade
def forfechahora(fecha):
        """transforma el formato de la fecha a uno legible"""
        cadena = fecha[0:4] + "-" + fecha[4:6] + "-" + fecha[6:8] \
            + " " + fecha[8:10] + ":" + fecha[10:12] + ":" +fecha[12:14]
        return cadena
        

def Cargando(d,data,desde,hasta):
    #---------data = [(col, dic),(),(),()...]
    gesbd = gesbbdd.gestion(BASEDEDATOS)
    baserows = gesbd.Rango(desde,hasta,"fechahora")
    for e,dic in enumerate(baserows):
        for key in colnames:
            d[key] = dic[key]
        data.append((str(e), d))
        d = {}

class MegaTable(Grid.PyGridTableBase):
    """
    A custom wx.Grid Table using user supplied data
    """
    def __init__(self, data, colnames):
        """data is a list of the form
        [(rowname, dictionary),
        dictionary.get(colname, None) returns the data for column
        colname
        """
        # The base class must be initialized *first*
        Grid.PyGridTableBase.__init__(self)
        self.data = data
        self.colnames = colnames
        # we need to store the row length and column length to
        # see if the table has changed size
        self._rows = self.GetNumberRows()
        self._cols = self.GetNumberCols()

    def GetNumberCols(self):
        return len(self.colnames)

    def GetNumberRows(self):
        return len(self.data)

    def GetColLabelValue(self, col):
        return self.colnames[col]

    def GetRowLabelValue(self, row):
        return self.data[row][0]

    def GetValue(self, row, col):
        if self.GetColLabelValue(col) == "fechahora":
            return forfechahora(str(self.data[row][1].get("fechahora")))
        return str(self.data[row][1].get(self.GetColLabelValue(col)))

    def GetRawValue(self, row, col):
        return self.data[row][1].get(self.GetColLabelValue(col), "")

    def SetValue(self, row, col, value):
        self.data[row][1][self.GetColLabelValue(col)] = value

    def ResetView(self, grid):
        """
        (Grid) -> Reset the grid view.   Call this to
        update the grid if rows and columns have been added or deleted
        """
        grid.BeginBatch()

        for current, new, delmsg, addmsg in [
            (self._rows, self.GetNumberRows(), Grid.GRIDTABLE_NOTIFY_ROWS_DELETED, Grid.GRIDTABLE_NOTIFY_ROWS_APPENDED),
            (self._cols, self.GetNumberCols(), Grid.GRIDTABLE_NOTIFY_COLS_DELETED, Grid.GRIDTABLE_NOTIFY_COLS_APPENDED),
        ]:

            if new < current:
                msg = Grid.GridTableMessage(self,delmsg,new,current-new)
                grid.ProcessTableMessage(msg)
            elif new > current:
                msg = Grid.GridTableMessage(self,addmsg,new-current)
                grid.ProcessTableMessage(msg)
                self.UpdateValues(grid)

        grid.EndBatch()

        self._rows = self.GetNumberRows()
        self._cols = self.GetNumberCols()
        # update the column rendering plugins
        self._updateColAttrs(grid)

        # update the scrollbars and the displayed part of the grid
        grid.AdjustScrollbars()
        grid.ForceRefresh()


    def UpdateValues(self, grid):
        """Update all displayed values"""
        # This sends an event to the grid table to update all of the values
        msg = Grid.GridTableMessage(self, Grid.GRIDTABLE_REQUEST_VIEW_GET_VALUES)
        grid.ProcessTableMessage(msg)

    def _updateColAttrs(self, grid):
        """
        wx.Grid -> update the column attributes to add the
        appropriate renderer given the column name.  (renderers
        are stored in the self.plugins dictionary)

        Otherwise default to the default renderer.
        """
        col = 0

    # ------------------------------------------------------
    # begin the added code to manipulate the table (non wx related)

    def DeleteCols(self, cols):
        """
        cols -> delete the columns from the dataset
        cols hold the column indices
        """
        # we'll cheat here and just remove the name from the
        # list of column names.  The data will remain but
        # it won't be shown
        deleteCount = 0
        cols = cols[:]
        cols.sort()

        for i in cols:
            self.colnames.pop(i-deleteCount)
            # we need to advance the delete count
            # to make sure we delete the right columns
            deleteCount += 1

        if not len(self.colnames):
            self.data = []

    def DeleteRows(self, rows):
        """
        rows -> delete the rows from the dataset
        rows hold the row indices
        """
        deleteCount = 0
        rows = rows[:]
        rows.sort()

        for i in rows:
            self.data.pop(i-deleteCount)
            # we need to advance the delete count
            # to make sure we delete the right rows
            deleteCount += 1

    def SortColumn(self, col):
        """
        col -> sort the data based on the column indexed by col
        """
        name = self.colnames[col]
        _data = []

        for row in self.data:
            rowname, entry = row
            try:
                orden = entry.get(name,None).lower()
            except:
                pass
            _data.append((orden, row))

        _data.sort()
        self.data = []

        for sortvalue, row in _data:
            self.data.append(row)
    # end table manipulation code
    # ----------------------------------------------------------
# --------------------------------------------------------------------
# Sample Grid using a specialized table and renderers that can
# be plugged in based on column names

    
class MegaGrid(Grid.Grid):
    def __init__(self, parent, data, colnames):
        """parent, data, colnames, plugins=None
        Initialize a grid using the data defined in data and colnames
        (see MegaTable for a description of the data format)
        plugins is a dictionary of columnName -> column renderers.
        """
        # The base class must be initialized *first*
        Grid.Grid.__init__(self, parent, -1)
        self._table = MegaTable(data, colnames)
        self.SetTable(self._table)
        self.Bind(Grid.EVT_GRID_LABEL_RIGHT_CLICK, self.OnLabelRightClicked)
        self.SetColSize(0,130)
        self.SetColSize(1,130)
        self.SetColSize(2,50)
        self.SetColSize(3,60)
        self.SetColSize(4,45)
        self.SetColSize(5,45)
        self.SetColSize(6,45)
        self.SetColSize(7,45)
        self.SetColSize(8,45)
        self.SetColSize(9,45)
        self.SetColSize(10,45)
        self.SetColSize(11,45)
        
    def Reset(self):
        """reset the view based on the data in the table.  Call
        this when rows are added or destroyed"""
        self._table.ResetView(self)

    def OnLabelRightClicked(self, evt):
        # Did we click on a row or a column?
        row, col = evt.GetRow(), evt.GetCol()
        if row == -1: self.colPopup(col, evt)
        elif col == -1: self.rowPopup(row, evt)

    def rowPopup(self, row, evt):
        """(row, evt) -> display a popup menu when a row label is right clicked"""
        appendID = wx.NewId()
        deleteID = wx.NewId()
        x = self.GetRowSize(row)/2

        if not self.GetSelectedRows():
            self.SelectRow(row)

        menu = wx.Menu()
        xo, yo = evt.GetPosition()
        menu.Append(appendID, "Append Row")
        menu.Append(deleteID, "Delete Row(s)")

        def append(event, self=self, row=row):
            self._table.AppendRow(row)
            self.Reset()

        def delete(event, self=self, row=row):
            rows = self.GetSelectedRows()
            self._table.DeleteRows(rows)
            self.Reset()

        self.Bind(wx.EVT_MENU, append, id=appendID)
        self.Bind(wx.EVT_MENU, delete, id=deleteID)
        self.PopupMenu(menu)
        menu.Destroy()
        return

    def colPopup(self, col, evt):
        """(col, evt) -> display a popup menu when a column label is
        right clicked"""
        x = self.GetColSize(col)/2
        menu = wx.Menu()
        id1 = wx.NewId()
        sortID = wx.NewId()

        xo, yo = evt.GetPosition()
        self.SelectCol(col)
        cols = self.GetSelectedCols()
        self.Refresh()
        menu.Append(id1, "Delete Col(s)")
        menu.Append(sortID, "Sort Column")

        def delete(event, self=self, col=col):
            cols = self.GetSelectedCols()
            self._table.DeleteCols(cols)
            self.Reset()

        def sort(event, self=self, col=col):
            self._table.SortColumn(col)
            self.Reset()

        self.Bind(wx.EVT_MENU, delete, id=id1)
        if len(cols) == 1:
            self.Bind(wx.EVT_MENU, sort, id=sortID)
        self.PopupMenu(menu)
        menu.Destroy()
        return


        
class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.grid = MegaGrid(self, data, colnames)
        self.button_1 = wx.Button(self, -1, "Cargar")
        self.button_2 = wx.Button(self, -1, "Por Fecha")
        self.TxtDesde = wx.StaticText(self, -1, "Desde")
        self.datepicker_ctrl_1 = wx.DatePickerCtrl(self, -1)
        self.TxtHasta = wx.StaticText(self, -1, "Hasta")
        self.datepicker_ctrl_2 = wx.DatePickerCtrl(self, -1)
        
        menu = wx.Menu()
        item = menu.Append(-1, "Page Setup...\tF5",
            "Set up page margins and etc.")
        #self.Bind(wx.EVT_MENU, self.OnPageSetup, item)
        item = menu.Append(-1, "Print Setup...\tF6",
            "Set up the printer options, etc.")
        #self.Bind(wx.EVT_MENU, self.OnPrintSetup, item)
        item = menu.Append(-1, "Print Preview...\tF7",
            "View the printout on-screen")
        #self.Bind(wx.EVT_MENU, self.OnPrintPreview, item)
        item = menu.Append(-1, "Print...\tF8", "Print the document")
        #self.Bind(wx.EVT_MENU, self.OnPrint, item)
        menu.AppendSeparator()
        item = menu.Append(-1, "Salir", "Cerrar aplicación")
        self.Bind(wx.EVT_MENU, self.OnExit, item)

        menubar = wx.MenuBar()
        self.SetMenuBar(menubar)
        menubar.Append(menu,"&Archivo")
        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        self.Bind(wx.EVT_CLOSE, self.OnClose)
        self.Bind(wx.EVT_DATE_CHANGED, self.fechadesde, self.datepicker_ctrl_1)
        self.Bind(wx.EVT_DATE_CHANGED, self.fechahasta, self.datepicker_ctrl_2)
        self.Bind(wx.EVT_BUTTON, self.PorFecha, self.button_2)
   
    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Vista de Base de Datos ")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("images/database.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((-1, -1))
        self.grid.CreateGrid(10, 3)
        #self.grid.SetSelectionMode(wx.grid.Grid.wxGridSelectRows)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        bz1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        bz1.Add(self.grid, 1, wx.EXPAND, 0)
        sizer_1.Add(self.button_1, 0, 0, 0)
        sizer_1.Add(self.button_2, 0, 0, 0)
        sizer_1.Add((0, 0), 1, wx.EXPAND, 4)
        sizer_1.Add(self.TxtDesde, 0,  wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(self.datepicker_ctrl_1, 0, wx.DP_SHOWCENTURY, 0)
        sizer_1.Add(self.TxtHasta, 0,  wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(self.datepicker_ctrl_2, 0, 0, 0)
        bz1.Add(sizer_1, 0, wx.EXPAND, 0)
        self.SetSizer(bz1)
        self.Layout()
        # end wxGlade
        
    def fechadesde(self,evt):
        self.desde = evt.GetDate().Format("%Y%m%d%H%M%S")
        evt.Skip()
        
    def fechahasta(self,evt):
        date =  evt.GetDate()
        date.Day += 1
        self.hasta = date.Format("%Y%m%d%H%M%S")
        evt.Skip()

    def PorFecha(self,evt):
        print "mostrando desde: " + self.desde + "Hasta" + self.hasta
        data = []
        Cargando(d,data,self.desde,self.hasta)
        self.grid._table.data = data
        self.grid.Reset()
        pass
        
    def OnExit(self,event):
		self.Close()
		event.Skip()
	
    def OnClose(self, event):
        #~ print self.data._data
        event.Skip()

# end of class MyFrame

if __name__ == "__main__":
    #baserows = gesbd.Parecido("201006","fechahora","horainicio")
    colnames = ["fechahora", "vin", "modelo", "usuario", "F1Si","F1Sf","F2Si",\
        "F2Sf","F1Pi","F1Pf","F2Pi","F2Pf"]
    d = {}
    data = []
    fecha = wx.DateTime_Now()
    hoy = fecha.Format("%Y%m%d%H%M%S")
    if fecha.Month > 0:
        fecha.Month -= 1
    else:
        fecha.Year-=1
        fecha.Month = 11
    unmes = fecha.Format("%Y%m%d%H%M%S")
    Cargando(d,data,unmes,hoy)
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()

